### ISSUE TITLE
BUG! JOIN not working on my queries

### ISSUE THREAD

**Issue by MahdiPishguy** [vitusortner/floor#173]
i have two model as:

```dart
@Entity(tableName: 'barcodes', indices: [
  Index(value: ['id', 'barcode'])
])
class BarcodesEntity {
  @PrimaryKey(autoGenerate: true)
  final int id;

  String barcode;

  @ColumnInfo(name: 'session_id')
  int sessionId;

  @ColumnInfo(name: 'data_time')
  String dateTime;

  BarcodesEntity(this.id, this.barcode, this.sessionId, this.dateTime);
}
```
and

```dart
@Entity(tableName: 'sessions', indices: [
  Index(value: ['id'])
])
class SessionsEntity {
  @PrimaryKey(autoGenerate: true)
  final int id;

  @ColumnInfo(name: 'session_name')
  String sessionName;

  @ColumnInfo(name:'session_type')
  int sessionType;

  @ColumnInfo(name:'date_time')
  String dateTime;

  SessionsEntity(this.id, this.sessionName,this.sessionType, this.dateTime);
}
```

now i'm trying to make join between this models like with:

```dart
  @Query('SELECT * FROM sessions LEFT JOIN barcodes ON sessions.id = barcodes.sessionId ORDER BY id DESC')
  Stream<List> getAllSessionsStream();
```
this query only return `sessions` table data

how can i resolve this problem?

**Comment by vitusortner** [comment]
What do you want to achieve exactly?

**Comment by MahdiPishguy** [comment]
@vitusortner

join two table `sessions`  and barcodes witch that `sessions.id` = `barcodes.sessionId` to get all data and ordering by id desc, for example:

```dart
SELECT * FROM sessions JOIN barcodes ON sessions.id = barcodes.sessionId ORDER BY id DESC
```

**Comment by MahdiPishguy** [comment]
@vitusortner how can i use join and get all data from more tables?

**Comment by mqus** [comment]
Joins and especially Streams of join queries with are a difficult feature to implement, which is why we haven't done that until now. This makes this "bug" more of a feature request. 
As a feature request for this feature was already mentioned many times, I will be closing this as a duplicate. Look at #321 for finding the implementation details and at #94 for tracking this particular feature (taking arbitrary queries and parsing them into an object)
