### ISSUE TITLE
database objects can't extend classes

### ISSUE THREAD

**Issue by CiriousJoker** [vitusortner/floor#188]
This:
```
class A extends B {
  @PrimaryKey(autoGenerate: true)
  int id;
}

class B {
  int id;
```
will not work. Every time I query for A, its id will be null. Doesn't matter if it's a primary key or a manually set value. However, interestingly it does query correctly, just the returned result is overwritten somehow.

**Comment by vitusortner** [comment]
I'll verify this behavior and provide a fix as soon as possible. Thanks for your report!

**Comment by xzhorikx** [comment]
@vitusortner thanks for all the work you've put into this library! I didn't want to create a separate issue since my question is pretty related to topic, so I think I'll ask here: can `@Entity` objects be extended from "Base classes"?

In my case I have a base class for all entities that are stored in local DB
```
@dao
class BaseEntity {
  BaseEntity(this.id, this.createdAt, this.updatedAt);
  @PrimaryKey(autoGenerate: true)
  @ColumnInfo(name: 'id', nullable: false)
  final String id;
  @ColumnInfo(name: 'createdAt', nullable: false)
  final int createdAt;
  @ColumnInfo(name: 'updatedAt', nullable: true)
  final int updatedAt;
}
```

And I'd like to extend this class in all DB entity classes 

```
@Entity(
  tableName: 'user'
)
class UserData extends BaseEntity {
  UserData(this.token, id, createdAt, updatedAt) : super(id, createdAt, updatedAt);
  @ColumnInfo(name: 'token', nullable: true)
  final String token;
}
```

When running code generator it throws following error:
```
Error running FloorGenerator
There is no primary key defined on the entity UserData.
package:%my_package%/user_entity.dart:8:7
  ╷
8 │ class UserData extends BaseEntity {
               ^^^^^^^^^^
```

Even if I add `@primaryKey` annotation to `token` field the floor generator build still fails with 

```
Error running FloorGenerator
RangeError (index): Invalid value: Not in range 0..3, inclusive: 4
[INFO] Running build completed, took 129ms
```

What is the solution here? Do I really have to add all fields from `BaseEntity` manually to each database entity?

**Comment by vitusortner** [comment]
@xzhorikx currently, yes. I already started investigating and thinking about possible solutions for that problem though.

**Comment by ramsestom** [comment]
any news on this?
