### ISSUE TITLE
Range constraints: Specify a minimum and maximim version.

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#191]
Hello. 
floor_generator depends on analyzer ^0.38.2.
When I use floor_generator 0.8.0 with built_value_generator 6.7.1 I got an error:

> Because no versions of floor_generator match >0.8.0 <0.9.0 and floor_generator 0.8.0 depends on analyzer ^0.38.2, floor_generator ^0.8.0 requires analyzer ^0.38.2.
And because built_value_generator 6.7.1 depends on analyzer >=0.34.0 <0.37.0 and no versions of built_value_generator match >6.7.1 <7.0.0, floor_generator ^0.8.0 is incompatible with built_value_generator ^6.7.1.
So, because incognita depends on both built_value_generator ^6.7.1 and floor_generator ^0.8.0, version solving failed

Please use range constraints and specify a minimum and maximim version for dependencies.

More info [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages#package-versions)

**Comment by ReginFell** [comment]
I've faced with the same issue, not sure if ranged dependencies will be any better. 
Now we have bottom constrains, with ranged will have top constraints as well.

Consider just changing the minimum applicable version for analyzer. 
Looks like everything works fine with 0.34.0

https://github.com/vitusortner/floor/pull/194

**Comment by vitusortner** [comment]
As @ReginFell mentioned, setting range constraints doesn't solve the problem. We could use a lower version of the analyzer package until built_value_generator is updated.
How do you handle such problems?

**Comment by ReginFell** [comment]
Not sure if we can do anything to solve that. 
A temporary solution is to  reduce min supported version to be aligned with built_value (I think the majority of applications use it so can't be ignored)

I think the core problem is in built_value that can't be updated to ^0.38.2 at the moment because it depends on analyzer_plugin which has a top constraint to 0.38.0. 

I've made a PR to fix that and hopefully, they will merge it soon 
https://github.com/dart-lang/sdk/pull/38558/files

After that MR with the new analyzer_plugin could be made
