### ISSUE TITLE
Question regarding about join

### ISSUE THREAD

**Issue by Chr1st-oo** [vitusortner/floor#213]
I am just starting to learn your library and I think its pretty awesome.

I have a question though.
Suppose I have two Entities
```dart
@entity
class Customer {
  @PrimaryKey(autoGenerate: true)
  final int id;

  final String name;
}

@Entity(foreignKeys: [
  ForeignKey(
      childColumns: ["customer_id"],
      parentColumns: ["id"],
      entity: Customer)
])
class Order {
  @PrimaryKey(autoGenerate: true)
  final int id;
  final String itemName;
  @ColumnInfo(name: "customer_id")
  final int customerId;
}
```
And for example this will be my query on the DAO
```sql
SELECT Customer.name, Order.itemName 
FROM Order 
INNER JOIN Customer 
ON Customer.id = Order.customer_id
WHERE Order.customer_id = :customerId
```
How will I write the abstract method in the DAO so that it can take all the required values? Right now I'm thinking of using two queries (without using the join) and the other is creating another class (not Entity) that have all the required fields. Something like this:
```dart
class CustomerOrder {
  String itemName;
  String customerName;
}
```
and an abstract method on the DAO like this:
```dart
@Query("QUERY")
Future<CustomerOrder> foo(int customerId);
```

Will this approach work and with no possible bad effects in a long run?

If you can recommend a better approach than this please do.

Cheers! Thanks for your hard work!

**Comment by mqus** [comment]
This is currently only possible with DatabaseViews. But I am working on a under-the-hood improvement(#321) which would make the feature you describe possible. Nevertheless, we will be tracking this feature in #94.

**Comment by Bricktheworld** [comment]
Could you possibly give an example of how to use the DatabaseViews? I'm not sure how to go about doing a join @mqus

**Comment by mqus** [comment]
Let's go with the example above: there has to be a class which represents your result, like `CustomerOrder`. You have to annotate that class with `@DatabaseView('YOUR JOIN QUERY WITHOUT :PARAMETERS')` and add that view to the views field of the database annotation, like you would with an entity. The class for the exanple should look like the following(notice the missing where clause which previously filtered for the parameter. We'll add that later):

```dart
@DatabaseView(' SELECT Customer.name, Order.itemName FROM Order INNER JOIN Customer ON Customer.id = Order.customer_id')
class CustomerOrder {
  String itemName;
  String customerName;
}
```

This will create a virtual table in the database on which you can perform selects like on a real table. So the query in the dao only has to filter the databaseview on the parameter. For the example this looks like that:

```dart
@Query("SELECT * FROM CustomerOrder WHERE customer_id = :customerId ")
Future<CustomerOrder> foo(int customerId);
```

Actually, you don't really have to reference the view in the query of your dao method and could just use the full join query, as long as the view exists(which is necessary to keep e.g. Streams working as expected) and the structure of the class matches the query output, although I would not recommend to rely on it too much, since this is an implementation detail which could change in the future.
