### ISSUE TITLE
The method 'where' was called on null

### ISSUE THREAD

**Issue by Ezaldeen99** [vitusortner/floor#387]
So when I run ` flutter packages pub run build_runner build`

it is always failed with this message 

```
` flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 309ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 9.9s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 822ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.0s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 4.0s

[SEVERE] floor_generator:floor_generator on lib/home/prescription.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/pdf/invoice.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/home/home.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/casesManagment/edit_case.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/casesManagment/newCase.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/casesManagment/ViewCase.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/home/caes_item_widget.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/home/drawer.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/home/drawer.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/login/reg.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[SEVERE] floor_generator:floor_generator on lib/home/view_all.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[SEVERE] floor_generator:floor_generator on lib/main.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[SEVERE] floor_generator:floor_generator on lib/pdf/report.dart:

Unsupported operation: Cannot resolve file:///D:/android%20projects/doctors_memory/lib/pdf/invoice.dart; only "package" and "asset" schemes supported
[SEVERE] floor_generator:floor_generator on lib/pdf/view_pdf.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[SEVERE] floor_generator:floor_generator on lib/search/search.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[SEVERE] floor_generator:floor_generator on test/widget_test.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[INFO] 5.6s elapsed, 16/25 actions completed.
[INFO] 6.7s elapsed, 16/25 actions completed.
[INFO] 9.2s elapsed, 16/25 actions completed.
[INFO] 13.2s elapsed, 17/25 actions completed.
[INFO] 14.3s elapsed, 24/25 actions completed.
[INFO] Running build completed, took 14.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 48ms

[SEVERE] Failed after 14.4s
pub finished with exit code 1
`
'''
```
but it works fine and generate the `database.g.dart`, but when I add any argument to the `Dao` to make an ORDER BY sort it doesn't work, when I hard coded it like this it worked I searched about other problems and checked that Future<void> and Future<List<Case>> is already there, here is the dao file 
```

`import 'dart:async';

import 'package:floor/floor.dart';

import 'Case.dart';

@dao
abstract class Dao {
  @Query('SELECT * FROM cases ASC')
  Future<List<Case>> findAllPersons();

  // passing an object didn't work so I will make it hard codded (:arg) didn't work
  @Query('SELECT * FROM cases ORDER BY name ASC')
  Future<List<Case>> findAllByName();

  @Query('SELECT * FROM cases ORDER BY name DESC')
  Future<List<Case>> findAllByNameD();

  @Query('SELECT * FROM cases ORDER BY age ASC')
  Future<List<Case>> findAllByAge();

  @Query('SELECT * FROM cases ORDER BY age DESC')
  Future<List<Case>> findAllByAgeD();

  @Query('SELECT * FROM cases ORDER BY dateAdded ASC')
  Future<List<Case>> findAllByDate();

  @Query('SELECT * FROM cases ORDER BY dateAdded DESC')
  Future<List<Case>> findAllByDateD();

  @Query(
      'SELECT * FROM \(SELECT * FROM cases ORDER BY id DESC LIMIT 10)ORDER BY id DESC')
  Future<List<Case>> latestItems();

  @Query('SELECT * FROM cases WHERE name = :name')
  Future<Case> findPersonByName(String name);

  @Query('SELECT * FROM cases WHERE id = :id')
  Future<Case> findById(int id);

  @delete
  Future<int> deleteById(Case person);

  @Query('DELETE FROM cases')
  Future<void> deleteAll();

  @insert
  Future<void> insertPerson(Case person);

  @update
  Future<void> updatePerson(Case person);
}
`
```

**Comment by sanisloandras** [comment]
Getting the same error, and more. Currently the lib is unusable?

`C:\Users\Andras\AndroidStudioProjects\nennos_pizza>flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 244ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 7.6s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 633ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 2.6s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 2.6s

[SEVERE] floor_generator:floor_generator on test/widget_test.dart:

Unsupported operation: Cannot resolve file:///C:/Users/Andras/AndroidStudioProjects/nennos_pizza/lib/presentation/common/add_to_cart/add_to_cart_widget.dart; only "package" and "asset" schemes supported
[INFO] 4.6s elapsed, 2/18 actions completed.
[INFO] 6.3s elapsed, 11/26 actions completed.
[SEVERE] floor_generator:floor_generator on lib/main.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[INFO] 8.3s elapsed, 38/52 actions completed.
[SEVERE] floor_generator:floor_generator on lib/presentation/pizza_details/pizza_details_widget.dart:

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
[INFO] Running build completed, took 8.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 40ms

[SEVERE] Failed after 8.8s
pub finished with exit code 1
`

`Launching lib\main.dart on SM G970F in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

Compiler message:
lib/domain/db/database.g.dart:59:18: Error: Type 'StreamController' not found.
  _$AppDatabase([StreamController<String> listener]) {
                 ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:59:18: Error: Expected 0 type arguments.
  _$AppDatabase([StreamController<String> listener]) {
                 ^
lib/domain/db/database.g.dart:67:10: Error: Type 'sqflite.Database' not found.
  Future<sqflite.Database> open(String path, List<Migration> migrations,
         ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:133:9: Error: Type 'sqflite.DatabaseExecutor' not found.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: Type 'StreamController' not found.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: Expected 0 type arguments.
  final StreamController<String> changeListener;
        ^
lib/domain/db/database.g.dart:209:9: Error: Type 'sqflite.DatabaseExecutor' not found.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: Type 'StreamController' not found.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: Expected 0 type arguments.
  final StreamController<String> changeListener;
        ^
lib/domain/db/database.g.dart:59:18: Error: 'StreamController' isn't a type.
  _$AppDatabase([StreamController<String> listener]) {
                 ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:60:34: Error: Method not found: 'StreamController.broadcast'.
    changeListener = listener ?? StreamController<String>.broadcast();
                                 ^^^^^^^^^
lib/domain/db/database.g.dart:69:29: Error: The getter 'sqflite' isn't defined for the class '_$AppDatabase'.
 - '_$AppDatabase' is from 'package:nennospizza/domain/db/database.dart' ('lib/domain/db/database.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'sqflite'.
    final databaseOptions = sqflite.OpenDatabaseOptions(
                            ^^^^^^^
lib/domain/db/database.g.dart:92:35: Error: A value of type 'Future<Database>' can't be assigned to a variable of type 'FutureOr<invalid-type>'.
 - 'Future' is from 'dart:async'.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
 - 'FutureOr' is from 'dart:async'.
    return sqfliteDatabaseFactory.openDatabase(path, options: databaseOptions);
                                  ^
lib/domain/db/database.g.dart:133:9: Error: 'sqflite.DatabaseExecutor' can't be used as a type because 'sqflite' isn't defined.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: 'StreamController' isn't a type.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:209:9: Error: 'sqflite.DatabaseExecutor' can't be used as a type because 'sqflite' isn't defined.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: 'StreamController' isn't a type.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^

Compiler message:
lib/domain/db/database.g.dart:59:18: Error: Type 'StreamController' not found.
  _$AppDatabase([StreamController<String> listener]) {
                 ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:59:18: Error: Expected 0 type arguments.
  _$AppDatabase([StreamController<String> listener]) {
                 ^
lib/domain/db/database.g.dart:67:10: Error: Type 'sqflite.Database' not found.
  Future<sqflite.Database> open(String path, List<Migration> migrations,
         ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:133:9: Error: Type 'sqflite.DatabaseExecutor' not found.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: Type 'StreamController' not found.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: Expected 0 type arguments.
  final StreamController<String> changeListener;
        ^
lib/domain/db/database.g.dart:209:9: Error: Type 'sqflite.DatabaseExecutor' not found.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: Type 'StreamController' not found.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: Expected 0 type arguments.
  final StreamController<String> changeListener;
        ^
lib/domain/db/database.g.dart:59:18: Error: 'StreamController' isn't a type.
  _$AppDatabase([StreamController<String> listener]) {
                 ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:60:34: Error: Method not found: 'StreamController.broadcast'.
    changeListener = listener ?? StreamController<String>.broadcast();
                                 ^^^^^^^^^
lib/domain/db/database.g.dart:69:29: Error: The getter 'sqflite' isn't defined for the class '_$AppDatabase'.
 - '_$AppDatabase' is from 'package:nennospizza/domain/db/database.dart' ('lib/domain/db/database.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'sqflite'.
    final databaseOptions = sqflite.OpenDatabaseOptions(
                            ^^^^^^^
lib/domain/db/database.g.dart:92:35: Error: A value of type 'Future<Database>' can't be assigned to a variable of type 'FutureOr<invalid-type>'.
 - 'Future' is from 'dart:async'.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
 - 'FutureOr' is from 'dart:async'.
    return sqfliteDatabaseFactory.openDatabase(path, options: databaseOptions);
                                  ^
lib/domain/db/database.g.dart:133:9: Error: 'sqflite.DatabaseExecutor' can't be used as a type because 'sqflite' isn't defined.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:135:9: Error: 'StreamController' isn't a type.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:209:9: Error: 'sqflite.DatabaseExecutor' can't be used as a type because 'sqflite' isn't defined.
  final sqflite.DatabaseExecutor database;
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/domain/db/database.g.dart:211:9: Error: 'StreamController' isn't a type.
  final StreamController<String> changeListener;
        ^^^^^^^^^^^^^^^^
`

**Comment by vitusortner** [comment]
Hi! This issue sometimes seems to occur after moving files. Imports similar to `file:///D:/android%20projects/doctors_memory/lib/pdf/invoice.dart` aren't supported and should be replaced with package imports.

**Comment by Ezaldeen99** [comment]
@vitusortner  solution worked, I'll close this issue
