### ISSUE TITLE
Rename columns (and tables) in migration

### ISSUE THREAD

**Issue by marcjoha** [vitusortner/floor#421]
Hi, thanks for this library. Elegant and easy to use!

I'm encountering problems trying to rename a column. I'm updating my dao from old to new property names, re-running the code generator, bumping the database version and running a migration similar to:

`await db.execute('ALTER TABLE Post RENAME COLUMN read TO isRead');`

However, this will invariably cause an error like this:

`SqfliteDatabaseException (DatabaseException(near "COLUMN": syntax error (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE Post RENAME COLUMN read TO isRead) sql 'ALTER TABLE Post RENAME COLUMN read TO isRead' args []})`

I've got plenty of other migrations, where I'm modifying actual data, so I know that piece works -- but I can't make renaming columns or table names work.

Any ideas?

**Comment by mqus** [comment]
Read is probavly a keyword, you'll have to use "read" or something similar

**Comment by mqus** [comment]
So ok, I'm on my PC and looked it up: https://sqlite.org/lang_keywords.html neither `read` nor `post` are keywords, so the first advice was wrong. The only other way this might throw a syntax exception might be if the column does not exist (anymore), since I can't see any inconsistencies in the query itself([SQLite Reference](https://sqlite.org/lang_altertable.html)). Could you provide more code snippets?

I also want to confirm the usual migration order that we expect:
1. Write all code(entities, dao, etc), SQL-Statements and everything else for version 1 and put `version: 1` in the `@Database` annotation.
2. Run Code generation for floor
3. Build&Install/Deploy(and use) the application (which causes the tables to be created and possibly filled with data)

Now the actual migration:

4. Alter the entities/views (the code in the dart classes) in the way you want them to be in the future
5. Alter the daos to fit the new entities/usecases
6. Write a migration function and put it into the floor db builder chain(with start and end version being 1 and 2, respectively).
7. Put `version: 2` into the `@Database` annotation (instead of `version: 1`).
8. Run Code generation
9. Build&Install/Deploy the new Code you just wrote. This will automatically either:
    - Create the new version 2 Tables if the app was not installed before
    - Run your migration functions, if the app was installed and the database was v1
    - Do nothing if the app was installed and the database was v1.

Obviously, steps 4-7 can be reordered at will, it's just a list of things you'll have to do. We also have implicit assumptions about the version numbers, but the simple guide is: don't skip versions and do only incremental migrations (e.g. not 2->4) and you're fine.

**Comment by vitusortner** [comment]
Renaming columns has been introduced in SQLite 3.25.0. If you're running your code on Android, there is no way to use these statements because Android comes with a lower SQLite version (depending on the Android version). You can find more information here https://developer.android.com/reference/android/database/sqlite/package-summary.html

In short: there is no way to use these statements on SQLite databases prior to 3.25.0. You can get around these limitations by following the steps described in the second part of this website https://www.sqlitetutorial.net/sqlite-rename-column/

**Comment by marcjoha** [comment]
Okay, that explains it. Thank you both for taking the time to investigate and reply!
