### ISSUE TITLE
Floor with Freezed

### ISSUE THREAD

**Issue by Crewlan** [vitusortner/floor#481]
I have a question, is walking with Freezed/Freezed annotation working ??

I am trying to save the data offline using Frezzed and Floor, but without success because the implementation of the entity in the database does not find the entity inside my freezed. Can someone help me?

Example

import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../../core/utils/date_utils.dart';
import '../../../../core/utils/mapper.dart';

part 'name_model.freezed.dart';
part 'name_model.g.dart';

@freezed
abstract class nameModel with _$nameModel {
  @entity
  const factory nameModel({
    @primaryKey String customerId,
    bool deleted,
    String description,
    String originalId,
    String resume,
  }) = _nameModel;
  factory nameModel.fromJson(Map<String, dynamic> json) => _$nameModelFromJson(json);
}

**Comment by Crewlan** [comment]
In the database it is not able to generate the .g.dart because it accuses that it has no entities

**Comment by vitusortner** [comment]
Hi! Freezed models are currently not supported in Floor. The problem is that we (currently) need the implementation of a class which means the abstract parent is not sufficient. It's tricky to tell how much of an investment it would be to support Freezed as I'm not familiar with its API surface.
Do you have more experience with Freezed? You can create a PR with the necessary changes to support Freezed in Floor. We're open for contributions!

**Comment by Crewlan** [comment]
@vitusortner I will do make some tests, any news I will update here

**Comment by knvpk** [comment]
Hi any progress on this, in my project there are many freezed classes, if freezed is not supported by floor, then need to write all classes again.

**Comment by Tokenizer94** [comment]
Still no support for Freezed package?

**Comment by Hennythehun** [comment]
It's a shame that Floor does not work with freezed yet. Has anyone come up with a workaround to this? I can't see myself using Floor over Freezed due to the power of its immutability, union types, and serialization. Using both right now gives me the following error:

"Entities and views are not allowed to inherit from mixins."
