### ISSUE TITLE
Can I access floor database from platform specific android code?

### ISSUE THREAD

**Issue by anayajoshi** [vitusortner/floor#493]
Hello,
I am using **floor** database in my flutter application. 
Also I have some platfrom specific code in android section of the application, where I am using **ROOM** database.
I have kept both the database names same. But they are working differently.
I want to keep the same database for both sections flutter and ROOM. 
Is it possible? or is there any other method to keep the same database for both the sections.
Please guide?

**Comment by vitusortner** [comment]
Hi! I don't have any experience with the described scenario. Can you find out where these two files are located?

**Comment by mqus** [comment]
I'll close this issue since you did not answer for so long. I think keeping room and floor in sync will be difficult and you should rather make sure that you're only using room OR floor and write an adapter from flutter to android yourself, at a higher level.

Why do I think that this will not work? Both libraries do not assume shared access of the database file (afaik). At the very least the reactive part (Streams in floor and maybe livedata in room) will not work flawlessly, you'll have to decide which library does the migrations and I'm not even sure if this really works (the ways room and floor determine the database version is probably incompatible). The other part is feature-parity, room has much more features than floor and many of those will not easily map to floor.

And viewed as a whole, I think this is purely architecturally a nightmare, since you have to manually sync the schema across both parts.

But as I wrote in the first sentence, since you did not answer or describe your usecase better we can only guess :cry: . Feel free to reopen if you have updates :)
